# Generated by Django 5.0.6 on 2024-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('publisher', models.CharField()),
                ('rating', models.CharField()),
                ('category', models.CharField()),
                ('image', models.CharField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
